name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: read
      id-token: write
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Dar permissao no Gradle Wrapper
        run: chmod +x gradlew

      - name: Injetar Credenciais no Gradle Global
        run: |
          mkdir -p ~/.gradle
          echo "gpr.user=${{ github.actor }}" >> ~/.gradle/gradle.properties
          echo "gpr.key=${{ secrets.GH_TOKEN }}" >> ~/.gradle/gradle.properties

      - name: Testar Compilacao dos Patches
        run: ./gradlew :patches:buildAndroid -Dgpr.user=${{ github.actor }} -Dgpr.key=${{ secrets.GH_TOKEN }}

      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        id: release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GPR_USER: ${{ github.actor }}
          GPR_KEY: ${{ secrets.GH_TOKEN }}
          GRADLE_OPTS: "-Dgpr.user=${{ github.actor }} -Dgpr.key=${{ secrets.GH_TOKEN }}"
          GIT_AUTHOR_NAME: semantic-release-bot
          GIT_AUTHOR_EMAIL: semantic-release-bot@martynus.net
          GIT_COMMITTER_NAME: semantic-release-bot
          GIT_COMMITTER_EMAIL: semantic-release-bot@martynus.net

      - name: Attest
        if: steps.release.outputs.new_release_published == 'true'
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: 'Piko Patches ${{ steps.release.outputs.new_release_git_tag }}'
          subject-path: patches/build/libs/patches-*.mpp
